server:
  port: 8100
  servlet:
    context-path: /auth

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  sleuth:
    sampler:
      probability: 1 # 采样率100%

  zipkin:
    enabled: false
    base-url: http://localhost:9411/ # Zipkin Server 地址
    discovery-client-enabled: false #让nacos把它当成一个URL，而不要当做服务名
    message-timeout: 5
    sender:
      type: web

dubbo:
  application:
    id: zsh-cloud-auth-server
    name: zsh-cloud-auth-server
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
    check: false
    parameters:
      # 命名空间ID
      namespace: 9af03680-d667-47c6-9b1d-bc5f88bfd5fd
  consumer:
    timeout: 30000
    retries: 5
  provider:
    filter: dubboExceptionFitler,-exception
  cloud:
    subscribed-services: 'zsh-cloud-system-server'

