server:
  port: 8100
#  servlet:
#    context-path: /auth

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    id: zsh-cloud-auth-server
    name: zsh-cloud-auth-server
    qos-enable: false

  protocol:
    name: dubbo
    port: -1

  registry:
    address: nacos://127.0.0.1:8848
    check: false
    parameters:
      # 命名空间ID
      namespace: 9af03680-d667-47c6-9b1d-bc5f88bfd5fd

  consumer:
    timeout: 30000
    retries: 5
    check: false

  provider:
    filter: dubboExceptionFitler,-exception

