server:
  port: 5001

spring:
  security:
    user:
      name: "admin"
      password: "admin"

  boot:
    admin:
#      context-path: /monitor
      ui:
        title: ZshCloud监控服务

management:
  health:
    redis:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}