server:
  port: 9000
#  servlet:
#    context-path: /wechat


spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**

management:
  health:
    redis:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}