server:
  port: 8200
#  servlet:
#    context-path: /system

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    id: zsh-cloud-system-server
    name: zsh-cloud-system-server
    qos-enable: false

  registry:
    address: nacos://127.0.0.1:8848
    check: false
    parameters:
      # 命名空间ID
      namespace: 9af03680-d667-47c6-9b1d-bc5f88bfd5fd

  protocol:
    name: dubbo
    port: -1

  provider:
    filter: dubboExceptionFitler,-exception

  scan:
    basePackages: com.zsh.cloud.system.application

zsh:
  cloud:
    tenant:
      ignore-urls:
        - /auth/*
      ignore-tables:
        - "sys_tenant"
        - "sys_account"
        - "sys_menu"
        - "sys_resource"
